MVCTASK/Models/Products.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTASK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Prouduct_ShoppingCart = new HashSet<Prouduct_ShoppingCart>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        public string Quantity { get; set; }
        public string ImgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prouduct_ShoppingCart> Prouduct_ShoppingCart { get; set; }
    }
}

MVCTASK/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCTASK.Models;
using MVCTASK.ViewModels;

namespace MVCTASK.Controllers
{
    public class ProductsController : Controller
    {
        int id;
        private MVCTASKDataEntities db = new MVCTASKDataEntities();

        // GET: Products
        public ActionResult Index(int id)
        {
            ViewBag.id = id;
            TempData["id"]=id;
            TempData.Keep("id");
            this.id = id;
            return View(db.Products.ToList());
        }
        public ActionResult Add(int ProductId,int id)
        {
            ShoppingCarts cart = new ShoppingCarts();
            cart.UserId = id;
            cart.ProductID = ProductId;
            db.ShoppingCarts.Add(cart);
           int z= db.SaveChanges();
            return RedirectToAction("Index", new { id = id });
        }
        public ActionResult Search(SearchItem SearchItem)
        {
            ViewBag.id = SearchItem. id;
            IQueryable<Products> Products;
            Products = from e in db.Products
                        select e;
            if (!String.IsNullOrEmpty(SearchItem.searchString))
            {
                int result;
                int.TryParse(SearchItem.searchString, out result);
                if (result > 0)
                {
                    Products = from e in db.Products
                               where e.Price == result || e.Quantity == result.ToString()
                               select e;


                }
                else
                {
                    Products = from e in db.Products
                               where e.Name== SearchItem.searchString
                               select e;
                }


            }
            return View("Index",  Products);

        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Products/Create
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Name,Price,Quantity,ImgPath")] Products products, HttpPostedFileBase file,int id)
        {
          
            try
            {
               
                if (ModelState.IsValid)
                {
                if (file != null && file.ContentLength > 0)
                {  

                        string path = Path.Combine(Server.MapPath("~/Images"),
                                                   Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        products.ImgPath = file.FileName;
                        db.Products.Add(products);
                        db.SaveChanges();
                        return RedirectToAction("Index",new {id= id } );
                    }
                }
        }
                catch (Exception ex)
                {
                return View(products);
            }

            return View(products);



        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.id = TempData["id"];
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Name,Price,Quantity,ImgPath")] Products products)
        {
            if (ModelState.IsValid)
            {
                db.Entry(products).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = TempData["id"] });
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = TempData["id"] });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCTASK/Controllers/ShoppingCartController.cs
using MVCTASK.Models;
using MVCTASK.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCTASK.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        private MVCTASKDataEntities db = new MVCTASKDataEntities();

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplayeShoppingCart(int id)
        {
            ViewBag.id = id;
            var user = db.User.Find(id);
            decimal total = 0;
            var cart = new UserCart();
            var ProductList = from s in db.ShoppingCarts
                              join p in db.Products on s.ProductID equals p.id
                              where s.UserId == id
                              select p;

            cart.ShoppingCarts = ProductList.ToList();
            
            foreach (var item in ProductList)
            {
                total = total + item.Price;
            }
            cart.total = total;
            cart.name = user.name;
            return View(cart);
        }
      
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoppingCarts cart = db.ShoppingCarts.Where(s=>s.ProductID==id).FirstOrDefault();
            if (cart == null)
            {
                return HttpNotFound();
            }
            db.ShoppingCarts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("DisplayeShoppingCart", new { id = id });
        }


    }
}

MVCTASK/Views/Products/Create.cshtml
@model MVCTASK.Models.Products

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";

}

<h2>Create</h2>

@using (Html.BeginForm("Create",
                        "Products",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Products</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div style="margin-left:120px" class="form-group">
        <label>Image</label>
        
            <input type="file" name="file" id="file" />
        
    </div>

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index",new {id=ViewBag.id })
</div>

MVCTASK/Views/Products/Delete.cshtml
@model MVCTASK.Models.Products

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgPath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCTASK/Views/Products/Details.cshtml
@model MVCTASK.Models.Products

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgPath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCTASK/Views/Products/Edit.cshtml
@model MVCTASK.Models.Products

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index",new {id = ViewBag.id })
</div>

MVCTASK/Views/Products/Index.cshtml
@model IEnumerable<MVCTASK.Models.Products>

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    ViewBag.Title = "Index";
}
<br />
@using (Html.BeginForm("Search", "Products", FormMethod.Get))
{<div class="col-md-12">
        <div class="col-md-3">
            @Html.TextBox("SearchString") <br />
        </div>
    <input type="hidden" name="id"value="@ViewBag.id" />
        <div class="col-md-3">

            <input type="submit" value="Search" />
        </div>
    </div>


}
<br /><br />
     
      <h2>
          <a href='@Url.Action("DisplayeShoppingCart", "ShoppingCart", new { id = ViewBag.id })'>
              <input type='button' class="btn btn-primary" value='Shopping Cart' />
          </a>
      </h2>
<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.id })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayName("Image")

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <img class="img-rounded" style="width:50px;height:50px" src="@Url.Content("~/Images/"+item.ImgPath)" alt="IMAGES" />
            </td>
            <td>
                <input type="hidden" name="id" />
                <a href="@Url.Action("Add","Products",new {ProductId=item.id,ViewBag.id })" class="btn btn-success">Add</a>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>